### ISSUE TITLE
TypeError: socket.on is not a function

### ISSUE THREAD

**Issue by linonetwo** [noflo/noflo#1045]
When using noflo js library, this code gets error

```
useRunGraph.ts:39 TypeError: socket.on is not a function
    at InPort.attachSocket (InPort.js:44:1)
    at InPort.attach (BasePort.js:105:1)
```

code is

```js
import { IP } from 'noflo';
import type { Network } from 'noflo/lib/Network';
import { createUIEffectsContext } from './debugUIEffectsContext';
import { uiStore } from './store';

/**
 * Inject prepared debugUIEffectsContext to the graph that is about to run.
 * UI effect Plugins should be added before this function is called, so they can show up in the debugUIEffectsContext.
 */
export function injectUIEffectsWhenRunGraph(nofloNetwork: Network) {
  const debugUIEffectsContext = createUIEffectsContext(uiStore);
  for (const componentName in nofloNetwork.processes) {
    const networkProcess = nofloNetwork.processes[componentName];
    networkProcess?.component?.inPorts?.ports?.ui_effects?.attach(new IP('data', debugUIEffectsContext));
  }
}
```

**Comment by linonetwo** [comment]
`attach` lacks Typescript type check, it is `any`, but should be `Socket`!

**Comment by linonetwo** [comment]
This seem to solved it by GPT3.5

```ts
import { IP } from 'noflo';
import { InternalSocket } from 'noflo/lib/InternalSocket';
import type { Network } from 'noflo/lib/Network';
import { createUIEffectsContext } from './debugUIEffectsContext';
import { uiStore } from './store';

/**
 * Inject prepared debugUIEffectsContext to the graph that is about to run.
 * UI effect Plugins should be added before this function is called, so they can show up in the debugUIEffectsContext.
 */
export function injectUIEffectsWhenRunGraph(nofloNetwork: Network) {
  const debugUIEffectsContext = createUIEffectsContext(uiStore);
  for (const componentName in nofloNetwork.processes) {
    const networkProcess = nofloNetwork.processes[componentName];
    const uiEffectsSocket = new InternalSocket(); // Create a new socket
    networkProcess?.component?.inPorts?.ports?.ui_effects?.attach(uiEffectsSocket);
    uiEffectsSocket.connect(); // Connect the socket

    // Now, you can send the debugUIEffectsContext using the socket
    uiEffectsSocket.send(new IP('data', debugUIEffectsContext));
  }
}
```
