### ISSUE TITLE
Journal issues with Array objects

### ISSUE THREAD

**Issue by djdeath** [noflo/noflo#152]
Some ports can be of type 'object' or 'array' which means it should be possible to send an empty array to them.
When doing so in the noflo-ui you get backtraces of storage problem : 

DOMException {message: "An object could not be cloned.", name: "DataCloneError", code: 25, stack: "Error: An object could not be cloned.↵    at IDBJo…0/bower_components/platform/platform.js:29:27537)", INDEX_SIZE_ERR: 1…}
 "Error: An object could not be cloned.
    at IDBJournalStore.putTransaction (http://localhost:1080/browser/noflo-ui.js:20154:17)
    at Journal.endTransaction (http://localhost:1080/browser/noflo-ui.js:6793:16)
    at Journal.endTransaction (http://localhost:1080/browser/noflo-ui.js:6401:59)
    at Graph.<anonymous> (http://localhost:1080/browser/noflo-ui.js:6766:22)
    at Graph.Emitter.emit (http://localhost:1080/browser/noflo-ui.js:336:20)
    at Graph.endTransaction (http://localhost:1080/browser/noflo-ui.js:3146:17)
    at Polymer.updateValue (http://localhost:1080/elements/noflo-node-inspector.html/noflo-node-inspector.js:188:22)
    at null.<anonymous> (http://localhost:1080/bower_components/platform/platform.js:34:16969)
    at t (http://localhost:1080/bower_components/platform/platform.js:29:28182)
    at r (http://localhost:1080/bower_components/platform/platform.js:29:27537)"

**Comment by bergie** [comment]
Moved to flowbased/fbp-graph#3 since Journal is now outside of NoFlo repo.
