### ISSUE TITLE
NoFlo Error : Component interaction/ListenChange not available with base path

### ISSUE THREAD

**Issue by TanyaJiyani** [noflo/noflo#642]
I wanted to run a NoFlo application. I created a noflo graph in JSON format and then tried to run it with the command: ./node_modules/.bin/noflo-nodejs --graph graphs/Number_game.json.

I got this error:
Component interaction/ListenChange not available with base C:\Users\hp\noflo_project\my-noflo-example
at ComponentLoader.load (C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\ComponentLoader.js:119:18)
at Network.load (C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\Network.js:149:26)
at Network.addNode (C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\Network.js:178:19)
at C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\Network.js:270:36
at C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\Network.js:281:20
at C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\Network.js:207:16
at C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\ComponentLoader.js:154:14
at Object.exports.dynamicLoad (C:\Users\hp\noflo_project\my-noflo-example\node_modules\noflo\lib\loader\NodeJs.js:199:10)

I have also tried installing the Component using this command :
npm install noflo-interaction --save
but still not working.
This happens every time whenever I add a new Component.

**Comment by trustmaster** [comment]
Closing as duplicate for #641, please continue the conversation there.
